version: '3.8'

services:
  app:
    build: .
    container_name: ecommerce_search
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - elasticsearch_esnet
    volumes:
      - ./:/app
      - ../kaggle_hm:/app/datasets/kaggle_hm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  elasticsearch_esnet:
    external: true